jobs:
  include:
    - name: github-pages
      if: branch = master
      language: python
      install:
        - pip install mkdocs mkdocs-material
      script:
        - mkdocs build
      deploy:
        provider: pages
        github_token: $GITHUB_TOKEN
        skip_cleanup: true
        keep_history: true
        local_dir: ./site
        on:
          branch: master